name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
        node-version: [12.x]
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "setup"
        run: |
          npm install -g lix
      - name: "installing"
        run: |
          cd test/unit/
          lix download haxe 4.0.5
          lix download haxe latest
          lix download haxe nightly
          lix download
      - name: "testing"
        run: |
          cd test/unit
          lix use haxe 4.0.5
          ./run.mac.sh
          lix use haxe latest
          ./run.mac.sh
          lix use haxe nightly
          ./run.mac.sh
        env:
          CI: true
