name: CI

on: [push, pull_request]

jobs:
  test-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "setup"
        run: |
          npm install -g lix
      - name: "installing"
        run: |
          cd test/unit/
          lix download haxe 4.0.5
          lix download haxe latest
          lix download haxe nightly
          lix download
      - name: "testing"
        run: |
          cd test/unit
          echo "Testing 4.0.5"
          lix use haxe 4.0.5
          ./run.win.bat
          ls
          ./app.exe
          # echo "Testing latest (via lix)"
          # lix use haxe latest
          # ./run.win.bat
          # echo "Testing nightly (via lix)"
          # lix use haxe nightly
          # ./run.win.bat
        env:
          CI: true

  test-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: "setup"
        run: |
          npm install -g lix
      - name: "installing"
        run: |
          cd test/unit/
          lix download haxe 4.0.5
          lix download haxe latest
          lix download haxe nightly
          lix download
      - name: "testing"
        run: |
          cd test/unit
          echo "Testing 4.0.5"
          lix use haxe 4.0.5
          ./run.mac.sh
          echo "Testing latest (via lix)"
          lix use haxe latest
          ./run.mac.sh
          echo "Testing nightly (via lix)"
          lix use haxe nightly
          ./run.mac.sh
        env:
          CI: true